version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "myst_parser"
        versions:
          - "4.0.0"
      - dependency-name: "pydantic"
        versions:
          - "2.10.5"
      - dependency-name: "pydantic-core"
        versions:
          - "2.27.2"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
